msaconfig:
  ipaddress: "192.168.10.3"
  dbtype: "oracle"
---

spring:
  profiles: local

msaconfig:
  ipaddress: "192.168.10.10"
  dbtype: "mysql"
  
---

spring:
  profiles: dev

msaconfig:
  ipaddress: "192.168.10.5"
  dbtype: "nosql"
---

